# This analysis template utilizes the job metric provider, which runs wrk (https://github.com/wg/wrk),
# an HTTP benchmarking tool, against the preview stack, then interprets the result.
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: load-test
spec:
  args:
  - name: service-name
  - name: duration
    value: 45s
  metrics:
  - name: load-test
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: load-tester
                image: argoproj/load-tester:latest
                command: [sh, -c, -x, -e]
                args:
                - |
                  wrk -t10 -c50 -d{{args.duration}} -s report.lua http://{{args.service-name}}/color
                  jq -e '.errors_ratio <= 0.05 and .latency_avg_ms < 100' report.json
              restartPolicy: Never
          backoffLimit: 0
