# This rollout starts an experiment which starts the new version as a preview stack, which receives
# no production traffic. While the preview stack is running, it simultaneously start 
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
spec:
  replicas: 5
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: canary-demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    canary:
      steps:
      - experiment:
          templates:
          - name: canary-preview
            specRef: canary
            selector:
              matchLabels:
                app: rollout-canary-preview
            metadata:
              labels:
                app: rollout-canary-preview
          analyses:
          - name: load-test
            templateName: load-test
