kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: exit-code-job
spec:
  args:
  - name: duration
    value: 0s
  - name: exit-code
    value: "1"
  metrics:
  - name: sleep-job
    initialDelay: 10s
    count: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep-job
                image: nginx:1.19-alpine
                command: [sh, -c, -x]
                args: ["sleep {{args.duration}} && exit {{args.exit-code}}"]
              restartPolicy: Never
          backoffLimit: 0
