apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
spec:
  strategy:
    replicas: 10
    canary:
      analysis:
        name: "analysis"
        templateName: "analysis-template"
      steps:
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
