apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: experiment-failure
spec:
  templates:
  - name: bad
    minReadySeconds: 60
    selector:
      matchLabels:
        app: canary-demo
    template:
      metadata:
        labels:
          app: canary-demo
      spec:
        containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:red
          args: [-cpu-burn, all]
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  analyses:
  - name: cpu-usage
    templateName: cpu-usage
